version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: saas-task-manager-db
    environment:
      POSTGRES_DB: taskmanagerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmanager_user -d taskmanagerdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: saas-task-manager-postgres-data