services:
  postgres:
    image: postgres:16
    container_name: saas-task-manager-db
    env_file:
      - /.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MAX_CONNECTIONS: 100
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-taskmanager_user} -d ${POSTGRES_DB:-taskmanagerdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - task-manager-network

volumes:
  postgres_data:
    name: saas-task-manager-postgres-data

networks:
  task-manager-network:
    name: task-manager-network